services:

  traefik:
    image: traefik:v2.11
    container_name: protosvpn-traefik
    restart: unless-stopped

    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

      - "--certificatesresolvers.letsencrypt.acme.email=dmitrynsu@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/letsencrypt/acme.json

    networks:
      - protosvpn-network

  api:
    build:
      context: ../api

    container_name: protosvpn-api
    restart: unless-stopped

    expose:
      - "8080"

    networks:
      - protosvpn-network

    labels:
    - "traefik.enable=true"

    - "traefik.http.routers.api.rule=Host(`protosvpn.novikoff.org`) && PathPrefix(`/api`)"

    - "traefik.http.routers.api.entrypoints=websecure"

    - "traefik.http.routers.api.tls.certresolver=letsencrypt"

    - "traefik.http.services.api.loadbalancer.server.port=8080"

    volumes:
      - ../vpn/data:/vpn-data:ro
      - ../vpn/data:/etc/openvpn
      - /var/run/docker.sock:/var/run/docker.sock
      
    environment:
      DATABASE_URL: postgres://protosvpn:protosvpn_password@postgres:5432/protosvpn
      JWT_SECRET: super-ultra-production-secret-key

  web:
    build:
      context: ../web

    container_name: protosvpn-web
    restart: unless-stopped

    depends_on:
      - api

    labels:
      - "traefik.enable=true"

      - 'traefik.http.routers.web.rule=Host("protosvpn.novikoff.org")'
      - "traefik.http.routers.web.entrypoints=websecure"

      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"

      - "traefik.http.services.web.loadbalancer.server.port=3000"

    networks:
      - protosvpn-network

    environment:
     NEXT_PUBLIC_API_URL: http://api:8080

  postgres:
    image: postgres:16

    container_name: protosvpn-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: protosvpn
      POSTGRES_USER: protosvpn
      POSTGRES_PASSWORD: protosvpn_password

    volumes:
      - postgres-data:/var/lib/postgresql/data

    expose:
      - "5432"

    networks:
      - protosvpn-network

  
      

  openvpn:
    image: kylemanna/openvpn

    container_name: protosvpn-openvpn
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun

    ports:
      - "1194:1194/udp"

    volumes:
      - ../vpn/data:/etc/openvpn

    networks:
      - protosvpn-network

networks:
  protosvpn-network:
    driver: bridge

volumes:
  postgres-data: